name: bulidVetLint

on:
  push:
    branches: [ main ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v2
        with:
          go-version: '1.17.2'

      - name: Install dependencies
        run: |
          cd v3
          go mod tidy
          go get -u golang.org/x/lint/golint

      - name: Build
        run: go build .

      - name: Run Vet & Lint
        run: |
          go vet .
          golint -set_exit_status=1 .
